# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
 # think of “push” as “trigger” 
  push:
    branches: 
      - 'feature/git_action'
 # “pull_request” as “pr”
  pull_request:
    branches: 
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.0
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.0"

    - name: Build Docker Images
      run: |
        docker build -t api-test . 

    - name: Test with pytest
      run: |
        
        docker run --workdir /home/docker/code -v "/home/docker/code":${{ github.workspace}} --name myservice -e API_TEST="main.py" api-test
        docker inspect myservice

    # - name: Copy Container file
    # docker run --workdir /home/docker/code --mount type=bind,source=$(pwd),destination=${{ github.workspace}} --name myservice -e API_TEST="main.py" api-test

    #   run: |         
    #     docker run --mount type=bind,source=/home/docker/code,destination=${{ github.workspace}} --name myservice api-test
    #     docker inspect myservice

    # - name: Copy Container file
    #   run: |       
    #     docker run --mount type=bind,source=$(pwd),destination=${{ github.workspace}} api-test
    #     docker inspect api-test



        
        
    # docker run --workdir ${{ github.workspace }} --rm -v "/home/docker/code":"/github/workflow" api-test
        
    
    # docker run -e API_TEST="main.py" api-test

    - name: Copy Container file
      run: |
        docker run -e API_TEST="main.py" api-test
        docker inspect myservice

    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: ${{ github.workspace }}/reports
        if-no-files-found: error
      if: ${{ always() }}





    