
name: Trigger Target Workflow
on:    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['judyye615/ADO_Artifact_Map']


    steps:
      - name: Trigger Workflow in Another Repository
        env: # Or as an environment variable
          TOKEN: ${{ secrets.PAT }}
        run: |
          curl -L \
          -X POST \ 
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer $env:TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ matrix.repo }}/actions/workflows/9664566992/" \
          --data-raw '{\"event_type\":\"dispatch-event\"}'

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; 
    
      - name: Test with pytest
        run: |
          pytest
