
name: Trigger Target Workflow
on:    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="judyye615" 
          repo_name="ADO_Artifact_Map"  
          curl -L \
          -X POST \ "https://api.github.com/repos/judyye615/ADO_Artifact_Map/dispatches" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d '{"event_type":"dispatch-event"}'


      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; 
    
      - name: Test with pytest
        run: |
          pytest
