# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
 # think of “push” as “trigger” 
  push:
    branches: 
      - 'feature/git_action'
 # “pull_request” as “pr”
  pull_request:
    branches: 
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.0
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.0"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest -vv main.py --html=./report/report.html --junit-xml=./report/test-results.xml

    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: ./report/
      if: ${{ always() }}


    - name: Publish Test Results  
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "./test-results.xml"


    